# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    # host:   P702-288-GJU\SQLEXPRESS    
      host:   172.20.6.3\SQLQUADRAN
    #login:   Dev
      login:   User_dev_GJU 
    #mdp:     Quadran1234
      mdp:     Exploitation34!
    #bdd:    REF_COM
      bdd:    REFERENTIEL_COM

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sie_central.dataManagerMySQL:
        class:  SIE\CentralBundle\DataManager\MySql
        arguments: [%host%, %login%, %mdp%,%bdd%]

        
    sie_equipement.dataManagerMySQL:
         class: SIE\EquipementBundle\DataManager\MySql
         arguments: [%host%, %login%, %mdp%,%bdd%]
    
    sie_contrat.dataManagerMySQL:
         class:  SIE\ContratBundle\DataManager\MySql
         arguments: [%host%, %login%, %mdp%,%bdd%]
    
    sie_access.dataManagerMySQL:
         class:  SIE\AccessBundle\DataManager\MySql
         arguments: [%host%, %login%, %mdp%,%bdd%]
         
    sie_document.dataManagerMySQL:
         class:  SIE\DocumentBundle\DataManager\MySql
         arguments: [%host%, %login%, %mdp%,%bdd%]
         
    sie_central.dataManagerSqlServeur:
        class:  SIE\CentralBundle\DataManager\SqlServeur
        arguments: [%host%, %login%, %mdp%,%bdd%]
        
    sie_equipement.dataManagerSqlServeur:
        class:  SIE\EquipementBundle\DataManager\SqlServeur
        arguments: [%host%, %login%, %mdp%,%bdd%]
    
    sie_contrat.dataManagerSqlServeur:
         class:  SIE\ContratBundle\DataManager\SqlServeur
         arguments: [%host%, %login%, %mdp%,%bdd%]
    
    sie_access.dataManagerSqlServeur:
         class:  SIE\AccessBundle\DataManager\SqlServeur
         arguments: [%host%, %login%, %mdp%,%bdd%]
         
    sie_document.dataManagerSqlServeur:
         class:  SIE\DocumentBundle\DataManager\SqlServeur
         arguments: [%host%, %login%, %mdp%,%bdd%]
         